language: scala

dist: trusty

scala:
  - 2.13.1
  - 2.12.10
  - 2.11.12

jdk:
  - oraclejdk8
  - oraclejdk11

services:
  - rabbitmq

sudo: false

cache:
  directories:
  - $HOME/.sbt
  - $HOME/.ivy2/cache
