language: scala

scala:
  - 2.12.8
  - 2.11.12

jdk:
  - openjdk7
  - openjdk8

# inspired by https://github.com/hashicorp/nomad-scala-sdk/blob/master/.travis.yml
matrix:
  exclude:
  # We build Scala 2.11 on Java 7, so let's not bother with Java 8
  - jdk: openjdk8
    scala: 2.11.12
  - jdk: openjdk7
    scala: 2.13.0

services:
  - rabbitmq

sudo: false

cache:
  directories:
  - $HOME/.sbt
  - $HOME/.ivy2/cache
